title: American Red Cross, International Services Department - Data Team
name: Data Team at American Red Cross International Services
description: ""
baseurl: ""
url: ""

collections:
  team:
    output: true
    permalimnk: /team/:path/

markdown: kramdown

exclude:
  - README.md