title: American Red Cross, International Services Department - Data Team
name: Data Team at American Red Cross International Services
description: ""
baseurl: ""
url: ""

permalink: /:categories/:year/:month/:day/:title/

collections:
  team:
    output: true
    permalimnk: /team/:path/

markdown: kramdown

exclude:
  - README.md

exclude:
  - bundle
  - Gemfile
  - Gemfile.lock
  - README.md